// AUTO-GENERATED by scripts/schema_fingerprint.py --emit-frozen
// VelaSchemaV3 的冻结（frozen）模型图快照：生成时与 live 图形逐属性一致。
// 规则：本文件内容禁止手工修改；模型变更时必须新建 VelaSchemaV(n+1) 后重新生成。
//
// 为什么需要冻结副本：SwiftData 的 VersionedSchema 一旦指向 live 类型，
// 任何字段增删都会改变历史 checksum，使存量 store 报告 unknown model version。
import Foundation
import SwiftData

/// 冻结的模型图快照（生成时与 live 图形完全一致）。
/// 注意：不要把它注册进 VelaMigrationPlan——SwiftData 拒绝 checksum 相
/// 同的两个 schema（Duplicate version checksums）。模型变更时：
///   1) 用本文件把变更前图形升级为 VersionedSchema（见 VelaModelContainer 注释）；
///   2) 新建 live 的 VelaSchemaV4 并加入计划；
///   3) python3 scripts/schema_fingerprint.py --update 更新黄金快照。
enum VelaSchemaV3Frozen {

    @Model
    final class AIReportRecord {
        var createdAt: Date
        var type: String
        var title: String
        var markdownContent: String
        var serializedContextSnapshot: String
        var serializedTags: String

        init(
            createdAt: Date,
            type: String,
            title: String,
            markdownContent: String,
            serializedContextSnapshot: String,
            serializedTags: String
        ) {
            self.createdAt = createdAt
            self.type = type
            self.title = title
            self.markdownContent = markdownContent
            self.serializedContextSnapshot = serializedContextSnapshot
            self.serializedTags = serializedTags
        }
    }

    @Model
    final class ActiveWorkoutDraftRecord {
        @Attribute(.unique) var id: UUID
        var title: String
        var startedAt: Date
        var templateId: UUID?
        @Attribute(.externalStorage) var exercisesJSON: String
        var notes: String
        var lastUpdated: Date

        init(
            id: UUID,
            title: String,
            startedAt: Date,
            templateId: UUID? = nil,
            exercisesJSON: String,
            notes: String,
            lastUpdated: Date
        ) {
            self.id = id
            self.title = title
            self.startedAt = startedAt
            self.templateId = templateId
            self.exercisesJSON = exercisesJSON
            self.notes = notes
            self.lastUpdated = lastUpdated
        }
    }

    @Model
    final class AgentArtifactRecord {
        @Attribute(.unique) var id: UUID
        var type: String
        var title: String
        var createdAt: Date
        var payloadJSON: String
        var sourceContextHash: String
        var status: String
        var confidence: Double
        var source: String
        var safetyNotice: String?

        init(
            id: UUID,
            type: String,
            title: String,
            createdAt: Date,
            payloadJSON: String,
            sourceContextHash: String,
            status: String,
            confidence: Double,
            source: String,
            safetyNotice: String? = nil
        ) {
            self.id = id
            self.type = type
            self.title = title
            self.createdAt = createdAt
            self.payloadJSON = payloadJSON
            self.sourceContextHash = sourceContextHash
            self.status = status
            self.confidence = confidence
            self.source = source
            self.safetyNotice = safetyNotice
        }
    }

    @Model
    final class AgentRunRecord {
        @Attribute(.unique) var id: UUID
        var agentName: String
        var startedAt: Date
        var endedAt: Date?
        var status: String
        var reason: String?
        var inputContextHash: String
        var outputSummary: String
        var toolCallsJSON: String
        var errorMessage: String?

        init(
            id: UUID,
            agentName: String,
            startedAt: Date,
            endedAt: Date? = nil,
            status: String,
            reason: String? = nil,
            inputContextHash: String,
            outputSummary: String,
            toolCallsJSON: String,
            errorMessage: String? = nil
        ) {
            self.id = id
            self.agentName = agentName
            self.startedAt = startedAt
            self.endedAt = endedAt
            self.status = status
            self.reason = reason
            self.inputContextHash = inputContextHash
            self.outputSummary = outputSummary
            self.toolCallsJSON = toolCallsJSON
            self.errorMessage = errorMessage
        }
    }

    @Model
    final class BiomarkerRecord {
        @Attribute(.unique) public var id: UUID
        public var name: String          // e.g., "Vitamin D", "Cortisol", "Ferritin", "Cholesterol"
        public var value: Double
        public var unit: String           // e.g., "ng/mL", "mcg/dL", "mg/dL"
        public var date: Date
        public var isOptimal: Bool
        public var referenceMin: Double
        public var referenceMax: Double
        public var sourceDocumentName: String? // Linked document name if OCR-extracted

        init(
            id: UUID,
            name: String,
            value: Double,
            unit: String,
            date: Date,
            isOptimal: Bool,
            referenceMin: Double,
            referenceMax: Double,
            sourceDocumentName: String? = nil
        ) {
            self.id = id
            self.name = name
            self.value = value
            self.unit = unit
            self.date = date
            self.isOptimal = isOptimal
            self.referenceMin = referenceMin
            self.referenceMax = referenceMax
            self.sourceDocumentName = sourceDocumentName
        }
    }

    @Model
    final class CoachArtifactRecord {
        @Attribute(.unique) var id: UUID
        var type: String
        var title: String
        var summary: String
        var createdAt: Date
        var relatedDate: Date?
        var decision: String?
        var confidence: Double
        var reasonsJSON: String
        var actionsJSON: String
        var sourceContextHash: String
        var userFeedback: String?
        var status: String
        var followUpQuestion: String?

        init(
            id: UUID,
            type: String,
            title: String,
            summary: String,
            createdAt: Date,
            relatedDate: Date? = nil,
            decision: String? = nil,
            confidence: Double,
            reasonsJSON: String,
            actionsJSON: String,
            sourceContextHash: String,
            userFeedback: String? = nil,
            status: String,
            followUpQuestion: String? = nil
        ) {
            self.id = id
            self.type = type
            self.title = title
            self.summary = summary
            self.createdAt = createdAt
            self.relatedDate = relatedDate
            self.decision = decision
            self.confidence = confidence
            self.reasonsJSON = reasonsJSON
            self.actionsJSON = actionsJSON
            self.sourceContextHash = sourceContextHash
            self.userFeedback = userFeedback
            self.status = status
            self.followUpQuestion = followUpQuestion
        }
    }

    @Model
    final class CoachInteractionRecord {
        @Attribute(.unique) var id: UUID
        var createdAt: Date
        var userText: String
        var assistantText: String
        var focus: String
        var contextHash: String?
        var sessionId: UUID?

        init(
            id: UUID,
            createdAt: Date,
            userText: String,
            assistantText: String,
            focus: String,
            contextHash: String? = nil,
            sessionId: UUID? = nil
        ) {
            self.id = id
            self.createdAt = createdAt
            self.userText = userText
            self.assistantText = assistantText
            self.focus = focus
            self.contextHash = contextHash
            self.sessionId = sessionId
        }
    }

    @Model
    final class CoachSessionRecord {
        @Attribute(.unique) var id: UUID
        var title: String
        var createdAt: Date
        var updatedAt: Date
        var serializedMessages: String
        var isArchived: Bool

        init(
            id: UUID,
            title: String,
            createdAt: Date,
            updatedAt: Date,
            serializedMessages: String,
            isArchived: Bool
        ) {
            self.id = id
            self.title = title
            self.createdAt = createdAt
            self.updatedAt = updatedAt
            self.serializedMessages = serializedMessages
            self.isArchived = isArchived
        }
    }

    @Model
    final class DailyDecisionFeedbackRecord {
        @Attribute(.unique) var dayIdentifier: String
        var planGeneratedAt: Date?
        var bodyStateHash: String
        var decisionType: String
        var decisionTitle: String
        var viewedAt: Date?
        var actionStartedAt: Date?
        var actionDestination: String?
        var adoptionStatus: String?
        var accuracyRating: String?
        var actualAction: String?
        var energyRating: Int?
        var fatigueRating: Int?
        var painRating: Int?
        var satisfactionRating: Int?
        var note: String
        var linkedWorkoutId: UUID?
        var createdAt: Date
        var updatedAt: Date

        init(
            dayIdentifier: String,
            planGeneratedAt: Date? = nil,
            bodyStateHash: String,
            decisionType: String,
            decisionTitle: String,
            viewedAt: Date? = nil,
            actionStartedAt: Date? = nil,
            actionDestination: String? = nil,
            adoptionStatus: String? = nil,
            accuracyRating: String? = nil,
            actualAction: String? = nil,
            energyRating: Int? = nil,
            fatigueRating: Int? = nil,
            painRating: Int? = nil,
            satisfactionRating: Int? = nil,
            note: String,
            linkedWorkoutId: UUID? = nil,
            createdAt: Date,
            updatedAt: Date
        ) {
            self.dayIdentifier = dayIdentifier
            self.planGeneratedAt = planGeneratedAt
            self.bodyStateHash = bodyStateHash
            self.decisionType = decisionType
            self.decisionTitle = decisionTitle
            self.viewedAt = viewedAt
            self.actionStartedAt = actionStartedAt
            self.actionDestination = actionDestination
            self.adoptionStatus = adoptionStatus
            self.accuracyRating = accuracyRating
            self.actualAction = actualAction
            self.energyRating = energyRating
            self.fatigueRating = fatigueRating
            self.painRating = painRating
            self.satisfactionRating = satisfactionRating
            self.note = note
            self.linkedWorkoutId = linkedWorkoutId
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class DailyHealthSummaryRecord {
        @Attribute(.unique) var dayIdentifier: String
        var date: Date
        var sleepScore: Double?
        var recoveryScore: Double?
        var strainScore: Double?
        var stressIndex: Double?
        var morningEnergy: Double?
        var currentEnergy: Double?
        var energyBank: Double?
        var configVersion: String
        var schemaVersion: Int
        var updatedAt: Date
        var createdAt: Date
        var healthAge: Double?
        var hrvAverage: Double?
        var hrvRmssdMilliseconds: Double?
        var restingHeartRate: Double?
        var sleepHours: Double?
        var deepSleepPercent: Double?
        var remSleepPercent: Double?
        var sleepEfficiency: Double?
        var steps: Double?
        var activeCalories: Double?
        var activeMinutes: Double?
        var workoutCount: Int?
        var workoutTypes: String?
        var workoutDuration: Double?
        var bodyWeight: Double?
        var bodyFatPercent: Double?
        var bmi: Double?
        var oxygenSaturation: Double?
        var respiratoryRate: Double?
        var wristTemperature: Double?
        var dailyLoad: Double?
        var workoutLoad: Double?
        var activityLoad: Double?
        var trainingLoadRatio: Double?
        var atl: Double?
        var ctl: Double?
        var tsb: Double?
        var acwr: Double?
        var bedtime: Date?
        var wakeTime: Date?
        var awakeMinutes: Double?
        var awakeEpisodeCount: Int?
        var deepSleepMinutes: Double?
        var remSleepMinutes: Double?
        @Attribute(.externalStorage) var workoutsData: Data?
        @Attribute(.externalStorage) var scoreEvidenceData: Data?

        init(
            dayIdentifier: String,
            date: Date,
            sleepScore: Double? = nil,
            recoveryScore: Double? = nil,
            strainScore: Double? = nil,
            stressIndex: Double? = nil,
            morningEnergy: Double? = nil,
            currentEnergy: Double? = nil,
            energyBank: Double? = nil,
            configVersion: String,
            schemaVersion: Int,
            updatedAt: Date,
            createdAt: Date,
            healthAge: Double? = nil,
            hrvAverage: Double? = nil,
            hrvRmssdMilliseconds: Double? = nil,
            restingHeartRate: Double? = nil,
            sleepHours: Double? = nil,
            deepSleepPercent: Double? = nil,
            remSleepPercent: Double? = nil,
            sleepEfficiency: Double? = nil,
            steps: Double? = nil,
            activeCalories: Double? = nil,
            activeMinutes: Double? = nil,
            workoutCount: Int? = nil,
            workoutTypes: String? = nil,
            workoutDuration: Double? = nil,
            bodyWeight: Double? = nil,
            bodyFatPercent: Double? = nil,
            bmi: Double? = nil,
            oxygenSaturation: Double? = nil,
            respiratoryRate: Double? = nil,
            wristTemperature: Double? = nil,
            dailyLoad: Double? = nil,
            workoutLoad: Double? = nil,
            activityLoad: Double? = nil,
            trainingLoadRatio: Double? = nil,
            atl: Double? = nil,
            ctl: Double? = nil,
            tsb: Double? = nil,
            acwr: Double? = nil,
            bedtime: Date? = nil,
            wakeTime: Date? = nil,
            awakeMinutes: Double? = nil,
            awakeEpisodeCount: Int? = nil,
            deepSleepMinutes: Double? = nil,
            remSleepMinutes: Double? = nil,
            workoutsData: Data? = nil,
            scoreEvidenceData: Data? = nil
        ) {
            self.dayIdentifier = dayIdentifier
            self.date = date
            self.sleepScore = sleepScore
            self.recoveryScore = recoveryScore
            self.strainScore = strainScore
            self.stressIndex = stressIndex
            self.morningEnergy = morningEnergy
            self.currentEnergy = currentEnergy
            self.energyBank = energyBank
            self.configVersion = configVersion
            self.schemaVersion = schemaVersion
            self.updatedAt = updatedAt
            self.createdAt = createdAt
            self.healthAge = healthAge
            self.hrvAverage = hrvAverage
            self.hrvRmssdMilliseconds = hrvRmssdMilliseconds
            self.restingHeartRate = restingHeartRate
            self.sleepHours = sleepHours
            self.deepSleepPercent = deepSleepPercent
            self.remSleepPercent = remSleepPercent
            self.sleepEfficiency = sleepEfficiency
            self.steps = steps
            self.activeCalories = activeCalories
            self.activeMinutes = activeMinutes
            self.workoutCount = workoutCount
            self.workoutTypes = workoutTypes
            self.workoutDuration = workoutDuration
            self.bodyWeight = bodyWeight
            self.bodyFatPercent = bodyFatPercent
            self.bmi = bmi
            self.oxygenSaturation = oxygenSaturation
            self.respiratoryRate = respiratoryRate
            self.wristTemperature = wristTemperature
            self.dailyLoad = dailyLoad
            self.workoutLoad = workoutLoad
            self.activityLoad = activityLoad
            self.trainingLoadRatio = trainingLoadRatio
            self.atl = atl
            self.ctl = ctl
            self.tsb = tsb
            self.acwr = acwr
            self.bedtime = bedtime
            self.wakeTime = wakeTime
            self.awakeMinutes = awakeMinutes
            self.awakeEpisodeCount = awakeEpisodeCount
            self.deepSleepMinutes = deepSleepMinutes
            self.remSleepMinutes = remSleepMinutes
            self.workoutsData = workoutsData
            self.scoreEvidenceData = scoreEvidenceData
        }
    }

    @Model
    final class DailyOperatingPlanRecord {
        @Attribute(.unique) var dayIdentifier: String
        var bodyStateHash: String
        var generatedAt: Date
        var primaryActionType: String
        var title: String
        var payloadJSON: String
        var reasonsJSON: String
        var confidence: Double
        var status: String
        var source: String?
        var safetyNotice: String?

        init(
            dayIdentifier: String,
            bodyStateHash: String,
            generatedAt: Date,
            primaryActionType: String,
            title: String,
            payloadJSON: String,
            reasonsJSON: String,
            confidence: Double,
            status: String,
            source: String? = nil,
            safetyNotice: String? = nil
        ) {
            self.dayIdentifier = dayIdentifier
            self.bodyStateHash = bodyStateHash
            self.generatedAt = generatedAt
            self.primaryActionType = primaryActionType
            self.title = title
            self.payloadJSON = payloadJSON
            self.reasonsJSON = reasonsJSON
            self.confidence = confidence
            self.status = status
            self.source = source
            self.safetyNotice = safetyNotice
        }
    }

    @Model
    final class DeletedWorkoutRecord {
        @Attribute(.unique) var id: String
        var deletedAt: Date

        init(
            id: String,
            deletedAt: Date
        ) {
            self.id = id
            self.deletedAt = deletedAt
        }
    }

    @Model
    final class ExerciseDefinitionRecord {
        @Attribute(.unique) var id: UUID
        var canonicalKey: String = ""
        var name: String
        var aliasesJSON: String
        var primaryMuscleGroup: String
        var secondaryMuscleGroupsJSON: String
        var equipment: String
        var movementPattern: String
        var isCustom: Bool
        var createdAt: Date
        var updatedAt: Date

        init(
            id: UUID,
            canonicalKey: String = "",
            name: String,
            aliasesJSON: String,
            primaryMuscleGroup: String,
            secondaryMuscleGroupsJSON: String,
            equipment: String,
            movementPattern: String,
            isCustom: Bool,
            createdAt: Date,
            updatedAt: Date
        ) {
            self.id = id
            self.canonicalKey = canonicalKey
            self.name = name
            self.aliasesJSON = aliasesJSON
            self.primaryMuscleGroup = primaryMuscleGroup
            self.secondaryMuscleGroupsJSON = secondaryMuscleGroupsJSON
            self.equipment = equipment
            self.movementPattern = movementPattern
            self.isCustom = isCustom
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class ExperimentCheckInRecord {
        @Attribute(.unique) var id: String
        var experimentID: UUID
        var dayIdentifier: String
        var date: Date
        var followedProtocol: Bool
        var note: String
        var createdAt: Date
        var updatedAt: Date

        init(
            id: String,
            experimentID: UUID,
            dayIdentifier: String,
            date: Date,
            followedProtocol: Bool,
            note: String,
            createdAt: Date,
            updatedAt: Date
        ) {
            self.id = id
            self.experimentID = experimentID
            self.dayIdentifier = dayIdentifier
            self.date = date
            self.followedProtocol = followedProtocol
            self.note = note
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class FoodLogRecord {
        @Attribute(.unique) var id: UUID
        var mealName: String
        var createdAt: Date
        var updatedAt: Date
        var source: String
        var totalCalories: Int
        var proteinGrams: Int
        var carbsGrams: Int
        var fatGrams: Int
        var fiberGrams: Int
        var healthScore: String
        var rawAnalysis: String
        var serializedFoods: String
        var serializedSuggestions: String

        init(
            id: UUID,
            mealName: String,
            createdAt: Date,
            updatedAt: Date,
            source: String,
            totalCalories: Int,
            proteinGrams: Int,
            carbsGrams: Int,
            fatGrams: Int,
            fiberGrams: Int,
            healthScore: String,
            rawAnalysis: String,
            serializedFoods: String,
            serializedSuggestions: String
        ) {
            self.id = id
            self.mealName = mealName
            self.createdAt = createdAt
            self.updatedAt = updatedAt
            self.source = source
            self.totalCalories = totalCalories
            self.proteinGrams = proteinGrams
            self.carbsGrams = carbsGrams
            self.fatGrams = fatGrams
            self.fiberGrams = fiberGrams
            self.healthScore = healthScore
            self.rawAnalysis = rawAnalysis
            self.serializedFoods = serializedFoods
            self.serializedSuggestions = serializedSuggestions
        }
    }

    @Model
    final class IntradaySignalBucketRecord {
        @Attribute(.unique) var id: String
        var dayIdentifier: String
        var signalRawValue: String
        var bucketStart: Date
        var bucketEnd: Date
        var average: Double
        var minimum: Double
        var maximum: Double
        var sampleCount: Int
        var unit: String
        var sourceIdentifier: String
        var sourceRevision: String
        var updatedAt: Date

        init(
            id: String,
            dayIdentifier: String,
            signalRawValue: String,
            bucketStart: Date,
            bucketEnd: Date,
            average: Double,
            minimum: Double,
            maximum: Double,
            sampleCount: Int,
            unit: String,
            sourceIdentifier: String,
            sourceRevision: String,
            updatedAt: Date
        ) {
            self.id = id
            self.dayIdentifier = dayIdentifier
            self.signalRawValue = signalRawValue
            self.bucketStart = bucketStart
            self.bucketEnd = bucketEnd
            self.average = average
            self.minimum = minimum
            self.maximum = maximum
            self.sampleCount = sampleCount
            self.unit = unit
            self.sourceIdentifier = sourceIdentifier
            self.sourceRevision = sourceRevision
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class JournalEntryRecord {
        var createdAt: Date
        var serializedTags: String
        var note: String
        var value: Double?
        var unit: String?

        init(
            createdAt: Date,
            serializedTags: String,
            note: String,
            value: Double? = nil,
            unit: String? = nil
        ) {
            self.createdAt = createdAt
            self.serializedTags = serializedTags
            self.note = note
            self.value = value
            self.unit = unit
        }
    }

    @Model
    final class MemoryEventRecord {
        @Attribute(.unique) var id: UUID
        var createdAt: Date
        var source: String
        var targetFile: String
        var memoryTypeRaw: String
        var operation: String
        var content: String
        var evidence: String
        var confidence: Double
        var status: String
        var userNote: String?
        var previousContent: String?
        var previousContentHash: String?
        var newContentHash: String?
        var linkedAgentRunId: String?

        init(
            id: UUID,
            createdAt: Date,
            source: String,
            targetFile: String,
            memoryTypeRaw: String,
            operation: String,
            content: String,
            evidence: String,
            confidence: Double,
            status: String,
            userNote: String? = nil,
            previousContent: String? = nil,
            previousContentHash: String? = nil,
            newContentHash: String? = nil,
            linkedAgentRunId: String? = nil
        ) {
            self.id = id
            self.createdAt = createdAt
            self.source = source
            self.targetFile = targetFile
            self.memoryTypeRaw = memoryTypeRaw
            self.operation = operation
            self.content = content
            self.evidence = evidence
            self.confidence = confidence
            self.status = status
            self.userNote = userNote
            self.previousContent = previousContent
            self.previousContentHash = previousContentHash
            self.newContentHash = newContentHash
            self.linkedAgentRunId = linkedAgentRunId
        }
    }

    @Model
    final class OnboardingState {
        @Attribute(.unique) var id: UUID
        var currentStep: String
        var isCompleted: Bool
        var completedAt: Date?
        var goalProfileJSON: String
        var trainingPreferenceJSON: String
        var equipmentProfileJSON: String
        var coachingPreferenceJSON: String
        var initialBodySnapshotJSON: String
        var missingDataJSON: String
        var firstBrief: String
        var firstActionPlanJSON: String
        var createdAt: Date
        var updatedAt: Date

        init(
            id: UUID,
            currentStep: String,
            isCompleted: Bool,
            completedAt: Date? = nil,
            goalProfileJSON: String,
            trainingPreferenceJSON: String,
            equipmentProfileJSON: String,
            coachingPreferenceJSON: String,
            initialBodySnapshotJSON: String,
            missingDataJSON: String,
            firstBrief: String,
            firstActionPlanJSON: String,
            createdAt: Date,
            updatedAt: Date
        ) {
            self.id = id
            self.currentStep = currentStep
            self.isCompleted = isCompleted
            self.completedAt = completedAt
            self.goalProfileJSON = goalProfileJSON
            self.trainingPreferenceJSON = trainingPreferenceJSON
            self.equipmentProfileJSON = equipmentProfileJSON
            self.coachingPreferenceJSON = coachingPreferenceJSON
            self.initialBodySnapshotJSON = initialBodySnapshotJSON
            self.missingDataJSON = missingDataJSON
            self.firstBrief = firstBrief
            self.firstActionPlanJSON = firstActionPlanJSON
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class PersonalExperimentRecord {
        @Attribute(.unique) var id: UUID
        var templateID: String
        var title: String
        var hypothesis: String
        var protocolText: String
        var targetBehaviorTag: String
        var primaryOutcome: String
        var startDate: Date
        var endDate: Date
        var baselineDays: Int
        var status: String
        var createdAt: Date
        var updatedAt: Date

        init(
            id: UUID,
            templateID: String,
            title: String,
            hypothesis: String,
            protocolText: String,
            targetBehaviorTag: String,
            primaryOutcome: String,
            startDate: Date,
            endDate: Date,
            baselineDays: Int,
            status: String,
            createdAt: Date,
            updatedAt: Date
        ) {
            self.id = id
            self.templateID = templateID
            self.title = title
            self.hypothesis = hypothesis
            self.protocolText = protocolText
            self.targetBehaviorTag = targetBehaviorTag
            self.primaryOutcome = primaryOutcome
            self.startDate = startDate
            self.endDate = endDate
            self.baselineDays = baselineDays
            self.status = status
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class ProactiveInsightRecord {
        @Attribute(.unique) public var id: UUID
        public var date: Date
        public var focusRaw: String
        public var severityRaw: String
        public var title: String
        public var bodyText: String
        public var suggestedAction: String?
        public var priority: Int
        public var coachPresetQuestion: String
        public var createdAt: Date

        init(
            id: UUID,
            date: Date,
            focusRaw: String,
            severityRaw: String,
            title: String,
            bodyText: String,
            suggestedAction: String? = nil,
            priority: Int,
            coachPresetQuestion: String,
            createdAt: Date
        ) {
            self.id = id
            self.date = date
            self.focusRaw = focusRaw
            self.severityRaw = severityRaw
            self.title = title
            self.bodyText = bodyText
            self.suggestedAction = suggestedAction
            self.priority = priority
            self.coachPresetQuestion = coachPresetQuestion
            self.createdAt = createdAt
        }
    }

    @Model
    final class SleepSummaryRecord {
        @Attribute(.unique) var dayIdentifier: String
        var date: Date
        var totalSleepMinutes: Int
        var bedtime: Date?
        var wakeTime: Date?
        var deepMinutes: Int?
        var remMinutes: Int?
        var coreMinutes: Int?
        var awakeMinutes: Int?
        var sleepScore: Double?
        var updatedAt: Date

        init(
            dayIdentifier: String,
            date: Date,
            totalSleepMinutes: Int,
            bedtime: Date? = nil,
            wakeTime: Date? = nil,
            deepMinutes: Int? = nil,
            remMinutes: Int? = nil,
            coreMinutes: Int? = nil,
            awakeMinutes: Int? = nil,
            sleepScore: Double? = nil,
            updatedAt: Date
        ) {
            self.dayIdentifier = dayIdentifier
            self.date = date
            self.totalSleepMinutes = totalSleepMinutes
            self.bedtime = bedtime
            self.wakeTime = wakeTime
            self.deepMinutes = deepMinutes
            self.remMinutes = remMinutes
            self.coreMinutes = coreMinutes
            self.awakeMinutes = awakeMinutes
            self.sleepScore = sleepScore
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class StrengthWorkoutRecord {
        @Attribute(.unique) var id: UUID
        var title: String
        var startedAt: Date
        var durationMinutes: Int
        var notes: String
        @Attribute(.externalStorage) var exercisesData: Data
        var linkedWorkoutEventId: UUID?
        var sourceTemplateId: UUID?
        var planDayId: UUID?
        var sessionRPE: Double?
        var completedAt: Date?
        var analyticsJSON: String?

        init(
            id: UUID,
            title: String,
            startedAt: Date,
            durationMinutes: Int,
            notes: String,
            exercisesData: Data,
            linkedWorkoutEventId: UUID? = nil,
            sourceTemplateId: UUID? = nil,
            planDayId: UUID? = nil,
            sessionRPE: Double? = nil,
            completedAt: Date? = nil,
            analyticsJSON: String? = nil
        ) {
            self.id = id
            self.title = title
            self.startedAt = startedAt
            self.durationMinutes = durationMinutes
            self.notes = notes
            self.exercisesData = exercisesData
            self.linkedWorkoutEventId = linkedWorkoutEventId
            self.sourceTemplateId = sourceTemplateId
            self.planDayId = planDayId
            self.sessionRPE = sessionRPE
            self.completedAt = completedAt
            self.analyticsJSON = analyticsJSON
        }
    }

    @Model
    final class TrainingPlanAdaptationRecord {
        @Attribute(.unique) var id: UUID
        var planId: UUID
        var dayId: UUID
        var createdAt: Date
        var adjustment: String  // keep, reduce, swap, rest, reschedule, deloadWeek
        var reason: String
        var suggestedAlternative: String?
        var status: String  // proposed, accepted, rejected
        var acceptedAt: Date?
        var rejectedAt: Date?
        var originalDayTitle: String
        var agentRunId: String?

        init(
            id: UUID,
            planId: UUID,
            dayId: UUID,
            createdAt: Date,
            adjustment: String,
            reason: String,
            suggestedAlternative: String? = nil,
            status: String,
            acceptedAt: Date? = nil,
            rejectedAt: Date? = nil,
            originalDayTitle: String,
            agentRunId: String? = nil
        ) {
            self.id = id
            self.planId = planId
            self.dayId = dayId
            self.createdAt = createdAt
            self.adjustment = adjustment
            self.reason = reason
            self.suggestedAlternative = suggestedAlternative
            self.status = status
            self.acceptedAt = acceptedAt
            self.rejectedAt = rejectedAt
            self.originalDayTitle = originalDayTitle
            self.agentRunId = agentRunId
        }
    }

    @Model
    final class TrainingPlanRecord {
        @Attribute(.unique) public var id: UUID
        public var title: String
        public var goalDescription: String
        public var startDate: Date
        public var weeksCount: Int
        public var isActive: Bool
        public var createdAt: Date
        public var updatedAt: Date
        public var serializedDays: String
        public var idempotencyKey: String?

        init(
            id: UUID,
            title: String,
            goalDescription: String,
            startDate: Date,
            weeksCount: Int,
            isActive: Bool,
            createdAt: Date,
            updatedAt: Date,
            serializedDays: String,
            idempotencyKey: String? = nil
        ) {
            self.id = id
            self.title = title
            self.goalDescription = goalDescription
            self.startDate = startDate
            self.weeksCount = weeksCount
            self.isActive = isActive
            self.createdAt = createdAt
            self.updatedAt = updatedAt
            self.serializedDays = serializedDays
            self.idempotencyKey = idempotencyKey
        }
    }

    @Model
    final class TrainingResponseRecord {
        @Attribute(.unique) var id: UUID
        var workoutId: UUID
        var date: Date
        var nextDayDate: Date
        var primaryMuscleGroupsJSON: String
        var totalEffectiveSets: Int
        var totalVolumeKg: Double
        var sessionRPE: Double?
        var nextDayRecoveryDelta: Double?
        var nextDayHRVDelta: Double?
        var nextDayRHRDelta: Double?
        var nextDaySleepScore: Double?
        var subjectiveTagsJSON: String
        var createdAt: Date

        init(
            id: UUID,
            workoutId: UUID,
            date: Date,
            nextDayDate: Date,
            primaryMuscleGroupsJSON: String,
            totalEffectiveSets: Int,
            totalVolumeKg: Double,
            sessionRPE: Double? = nil,
            nextDayRecoveryDelta: Double? = nil,
            nextDayHRVDelta: Double? = nil,
            nextDayRHRDelta: Double? = nil,
            nextDaySleepScore: Double? = nil,
            subjectiveTagsJSON: String,
            createdAt: Date
        ) {
            self.id = id
            self.workoutId = workoutId
            self.date = date
            self.nextDayDate = nextDayDate
            self.primaryMuscleGroupsJSON = primaryMuscleGroupsJSON
            self.totalEffectiveSets = totalEffectiveSets
            self.totalVolumeKg = totalVolumeKg
            self.sessionRPE = sessionRPE
            self.nextDayRecoveryDelta = nextDayRecoveryDelta
            self.nextDayHRVDelta = nextDayHRVDelta
            self.nextDayRHRDelta = nextDayRHRDelta
            self.nextDaySleepScore = nextDaySleepScore
            self.subjectiveTagsJSON = subjectiveTagsJSON
            self.createdAt = createdAt
        }
    }

    @Model
    final class UserWikiDocumentRecord {
        @Attribute(.unique) var filename: String
        var title: String
        var markdownContent: String
        var updatedAt: Date

        init(
            filename: String,
            title: String,
            markdownContent: String,
            updatedAt: Date
        ) {
            self.filename = filename
            self.title = title
            self.markdownContent = markdownContent
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class VelaEventRecord {
        @Attribute(.unique) var id: UUID
        var eventType: String
        var timestamp: Date
        var title: String
        var detail: String
        var metadataJSON: String

        init(
            id: UUID,
            eventType: String,
            timestamp: Date,
            title: String,
            detail: String,
            metadataJSON: String
        ) {
            self.id = id
            self.eventType = eventType
            self.timestamp = timestamp
            self.title = title
            self.detail = detail
            self.metadataJSON = metadataJSON
        }
    }

    @Model
    final class WorkoutEventRecord {
        @Attribute(.unique) public var id: UUID
        public var source: String // "healthKit" | "manual" | "strengthLog"
        public var startedAt: Date
        public var endedAt: Date
        public var dayIdentifier: String = ""
        public var activityType: String
        public var title: String = ""
        public var durationMinutes: Double = 0
        public var energyKilocalories: Double?
        public var averageHeartRate: Double?
        public var rpe: Double?
        public var linkedStrengthWorkoutId: UUID?
        public var linkedHealthKitWorkoutId: UUID?
        public var linkedTrainingPlanDayId: UUID?
        public var createdAt: Date = Date()
        public var updatedAt: Date = Date()

        init(
            id: UUID,
            source: String,
            startedAt: Date,
            endedAt: Date,
            dayIdentifier: String = "",
            activityType: String,
            title: String = "",
            durationMinutes: Double = 0,
            energyKilocalories: Double? = nil,
            averageHeartRate: Double? = nil,
            rpe: Double? = nil,
            linkedStrengthWorkoutId: UUID? = nil,
            linkedHealthKitWorkoutId: UUID? = nil,
            linkedTrainingPlanDayId: UUID? = nil,
            createdAt: Date = Date(),
            updatedAt: Date = Date()
        ) {
            self.id = id
            self.source = source
            self.startedAt = startedAt
            self.endedAt = endedAt
            self.dayIdentifier = dayIdentifier
            self.activityType = activityType
            self.title = title
            self.durationMinutes = durationMinutes
            self.energyKilocalories = energyKilocalories
            self.averageHeartRate = averageHeartRate
            self.rpe = rpe
            self.linkedStrengthWorkoutId = linkedStrengthWorkoutId
            self.linkedHealthKitWorkoutId = linkedHealthKitWorkoutId
            self.linkedTrainingPlanDayId = linkedTrainingPlanDayId
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }
    }

    @Model
    final class WorkoutTemplateRecord {
        @Attribute(.unique) var id: UUID
        var title: String
        var goal: String
        var notes: String
        var exercisesJSON: String
        var estimatedDurationMinutes: Int
        var createdAt: Date
        var updatedAt: Date
        var lastUsedAt: Date?

        init(
            id: UUID,
            title: String,
            goal: String,
            notes: String,
            exercisesJSON: String,
            estimatedDurationMinutes: Int,
            createdAt: Date,
            updatedAt: Date,
            lastUsedAt: Date? = nil
        ) {
            self.id = id
            self.title = title
            self.goal = goal
            self.notes = notes
            self.exercisesJSON = exercisesJSON
            self.estimatedDurationMinutes = estimatedDurationMinutes
            self.createdAt = createdAt
            self.updatedAt = updatedAt
            self.lastUsedAt = lastUsedAt
        }
    }

    @Model
    final class XunjiDailyCacheRecord {
        @Attribute(.unique) var datestr: String
        var fetchedAt: Date
        var includeFullData: Bool
        @Attribute(.externalStorage) var responseData: Data

        init(
            datestr: String,
            fetchedAt: Date,
            includeFullData: Bool,
            responseData: Data
        ) {
            self.datestr = datestr
            self.fetchedAt = fetchedAt
            self.includeFullData = includeFullData
            self.responseData = responseData
        }
    }

    @Model
    final class XunjiWorkoutMirrorRecord {
        @Attribute(.unique) var externalID: String
        var datestr: String
        var linkedStrengthWorkoutID: UUID?
        var linkedWorkoutEventID: UUID?
        @Attribute(.externalStorage) var rawTrainData: Data
        var lastImportedAt: Date

        init(
            externalID: String,
            datestr: String,
            linkedStrengthWorkoutID: UUID? = nil,
            linkedWorkoutEventID: UUID? = nil,
            rawTrainData: Data,
            lastImportedAt: Date
        ) {
            self.externalID = externalID
            self.datestr = datestr
            self.linkedStrengthWorkoutID = linkedStrengthWorkoutID
            self.linkedWorkoutEventID = linkedWorkoutEventID
            self.rawTrainData = rawTrainData
            self.lastImportedAt = lastImportedAt
        }
    }

    static var models: [any PersistentModel.Type] {
        [
            AIReportRecord.self,
            ActiveWorkoutDraftRecord.self,
            AgentArtifactRecord.self,
            AgentRunRecord.self,
            BiomarkerRecord.self,
            CoachArtifactRecord.self,
            CoachInteractionRecord.self,
            CoachSessionRecord.self,
            DailyDecisionFeedbackRecord.self,
            DailyHealthSummaryRecord.self,
            DailyOperatingPlanRecord.self,
            DeletedWorkoutRecord.self,
            ExerciseDefinitionRecord.self,
            ExperimentCheckInRecord.self,
            FoodLogRecord.self,
            IntradaySignalBucketRecord.self,
            JournalEntryRecord.self,
            MemoryEventRecord.self,
            OnboardingState.self,
            PersonalExperimentRecord.self,
            ProactiveInsightRecord.self,
            SleepSummaryRecord.self,
            StrengthWorkoutRecord.self,
            TrainingPlanAdaptationRecord.self,
            TrainingPlanRecord.self,
            TrainingResponseRecord.self,
            UserWikiDocumentRecord.self,
            VelaEventRecord.self,
            WorkoutEventRecord.self,
            WorkoutTemplateRecord.self,
            XunjiDailyCacheRecord.self,
            XunjiWorkoutMirrorRecord.self,
        ]
    }
}
