import Foundation

struct DailyLogEntry: Hashable {
    var date: Date
    var healthBrief: String
    var chatSummary: String
    var keyInsights: [String]
}

enum DailyLogService {
    private static var baseURL: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        return appSupport.appendingPathComponent("Vela", isDirectory: true)
            .appendingPathComponent("daily_logs", isDirectory: true)
    }

    private static var dateFormatter: DateFormatter {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        return f
    }

    private static var isoFormatter: ISO8601DateFormatter {
        ISO8601DateFormatter()
    }

    static func filename(for date: Date) -> String {
        "\(dateFormatter.string(from: date)).md"
    }

    static func url(for date: Date) -> URL {
        baseURL.appendingPathComponent(filename(for: date))
    }

    // MARK: - Read / Write

    static func write(dashboard: DashboardSummary, chatMessages: [CoachChatMessage], date: Date = Date()) throws {
        try FileManager.default.createDirectory(at: baseURL, withIntermediateDirectories: true)

        let healthSection = buildHealthSection(from: dashboard)
        let chatSection = buildChatSection(from: chatMessages)
        let insights = buildInsights(from: dashboard)

        let content = """
        # \(dateFormatter.string(from: date))

        ## Health Brief
        \(healthSection)

        ## Key Metrics
        - Recovery: \(dashboard.recovery.hasData ? "\(Int(dashboard.recovery.score.rounded()))/100 (\(dashboard.recovery.band.rawValue))" : "No data")
        - Sleep: \(dashboard.sleepScore.hasData ? "\(dashboard.sleepSummary.totalSleepMinutes / 60)h \(dashboard.sleepSummary.totalSleepMinutes % 60)m (Score: \(Int(dashboard.sleepScore.score.rounded())))" : "No data")
        - Strain: \(dashboard.strain.hasData ? "\(Int(dashboard.strain.score.rounded()))/100 (\(dashboard.strain.targetStatus.rawValue))" : "No data")
        - Stress: \(dashboard.stress.hasData ? "\(Int(dashboard.stress.stressIndex.rounded()))/100 (\(dashboard.stress.band.rawValue))" : "No data")
        - Energy: \(dashboard.energy.hasData ? "Morning: \(Int(dashboard.energy.morningEnergy.rounded())), Current: \(Int(dashboard.energy.currentEnergy.rounded()))" : "No data")

        ## Insights
        \(insights)

        ## Coach Conversation
        \(chatSection)

        ---
        Generated by Vela · \(isoFormatter.string(from: date))
        """

        try content.write(to: url(for: date), atomically: true, encoding: .utf8)
    }

    static func loadWeek(endingAt date: Date = Date(), calendar: Calendar = .current) -> [DailyLogEntry] {
        let today = calendar.startOfDay(for: date)
        guard let weekStart = calendar.date(byAdding: .day, value: -6, to: today) else { return [] }

        return (0...6).compactMap { offset in
            guard let day = calendar.date(byAdding: .day, value: offset, to: weekStart) else { return nil }
            let fileURL = url(for: day)
            guard let text = try? String(contentsOf: fileURL, encoding: .utf8) else { return nil }
            return parseEntry(from: text, date: day)
        }
    }

    static func loadDate(_ date: Date) -> DailyLogEntry? {
        guard let text = try? String(contentsOf: url(for: date), encoding: .utf8) else { return nil }
        return parseEntry(from: text, date: date)
    }

    // MARK: - Private Helpers

    private static func buildHealthSection(from dashboard: DashboardSummary) -> String {
        var lines: [String] = []

        lines.append("Source: \(dashboard.source.rawValue)")

        if dashboard.recovery.hasData {
            lines.append("Recovery reasons:")
            for reason in dashboard.recovery.reasons.prefix(3) {
                lines.append("- \(reason)")
            }
        }

        if dashboard.sleepScore.hasData {
            lines.append("Sleep: \(dashboard.sleepSummary.totalSleepMinutes / 60)h \(dashboard.sleepSummary.totalSleepMinutes % 60)m")
            if let bedtime = dashboard.sleepSummary.bedtime {
                let fmt = DateFormatter()
                fmt.dateFormat = "HH:mm"
                lines.append("Bedtime: \(fmt.string(from: bedtime))")
            }
            if let waketime = dashboard.sleepSummary.wakeTime {
                let fmt = DateFormatter()
                fmt.dateFormat = "HH:mm"
                lines.append("Waketime: \(fmt.string(from: waketime))")
            }
        }

        return lines.joined(separator: "\n")
    }

    private static func buildChatSection(from messages: [CoachChatMessage]) -> String {
        guard !messages.isEmpty else { return "No conversation today." }
        return messages.map { msg in
            "**\(msg.role == .user ? "User" : "Vela")**: \(msg.content.prefix(500))"
        }.joined(separator: "\n\n")
    }

    private static func buildInsights(from dashboard: DashboardSummary) -> String {
        var insights: [String] = []
        let recoveryBand = dashboard.recovery.band
        if recoveryBand == .low, dashboard.recovery.hasData {
            insights.append("- Recovery is low. Consider a rest day or lighter activity.")
        }
        if dashboard.strain.targetStatus == .aboveTarget, dashboard.strain.hasData {
            insights.append("- Strain is above the recommended range. Watch for overtraining.")
        }
        if dashboard.stress.band == .elevated || dashboard.stress.band == .high, dashboard.stress.hasData {
            insights.append("- Stress proxy is elevated. HRV or heart rate may indicate physiological strain.")
        }
        if dashboard.energy.status == .depleted || dashboard.energy.status == .low, dashboard.energy.hasData {
            insights.append("- Energy is low. Prioritize recovery and sleep tonight.")
        }
        return insights.isEmpty ? "No notable patterns today." : insights.joined(separator: "\n")
    }

    private static func parseEntry(from text: String, date: Date) -> DailyLogEntry {
        let healthBrief = extractSection("Health Brief", from: text)
        let chatSummary = extractSection("Coach Conversation", from: text)
        let insights = extractSection("Insights", from: text)
            .components(separatedBy: "\n")
            .filter { $0.hasPrefix("-") }
            .map { String($0.dropFirst(2)) }
        return DailyLogEntry(date: date, healthBrief: healthBrief, chatSummary: chatSummary, keyInsights: insights)
    }

    private static func extractSection(_ title: String, from text: String) -> String {
        guard let range = text.range(of: "## \(title)\n") else { return "" }
        let start = range.upperBound
        let rest = String(text[start...])
        if let nextRange = rest.range(of: "\n## ") {
            return String(rest[..<nextRange.lowerBound]).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return rest.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
